spring:
    datasource:
        url: jdbc:mysql://localhost:3306/leagueofphotosdb?characterEncoding=UTF-8&useSSL=false
        username: user
        password: user
        testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
        validationQuery: SELECT 1
    jpa:
        show-sql: false # Show or not log for each sql query
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
            jadira.usertype.autoRegisterUserTypes: true
    devtools.livereload.enabled: true

#security.user.password: passw0rd